### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Rifzzz178** [DeathAruban/Lore-Item-MCBE#1]
When my friend accidentally opened the admin lore item, he suddenly got stuck under the finished leaf sneak, then he opened the GUI for modifications but when I checked the server dashboard a spam message appeared as in the picture, so how do I solve it?
![Screenshot_2023-12-24-19-50-15-022_com android chrome](https://github.com/DeathAruban/Lore-Item-MCBE/assets/154742722/6c2eddaa-93f3-4cc2-81f7-5a8939d19d3b)

**Comment by DeathAruban** [comment]
the error shown in the log is not generated by my addon, the main.js file is not present in my component, in the log there is an error in the main.js file on line 139, in my component there are only 2 scrpit lore_item files. js and settings_lore.js, so the error will be for another addon that you inserted into the server on aternos

**Comment by Rifzzz178** [comment]
okay thanks
